### PR TITLE
Langium rules for structured text

### PR DESCRIPTION
**Pull request by rempAut**
WIP langium rules

### CODE REVIEW

**Comment by Serhioromano** [comment]
Thank you. I have not yet tested it but please update upstream. I deleted .gitignore since generated files have to be commited to github in order for action that builds extensions automatically works. Also syntax JSON file was lost, I have restored it.

**Comment by rempAut** [comment]
Had no intetions to merge yet, still want to  finish the ST statements part at least.

**Comment by Serhioromano** [comment]
> Had no intetions to merge yet, still want to finish the ST statements part at least.

No worries. Continue to develop and submit new PRs along the way for review. This is feature branch anyway. Just upstream from this branch to you to have updates I am working on this branch.

**Comment by rempAut** [comment]
There is a lot of mistakes. 
```
Signed_Integer returns number:
    ('+'|'-')? Integer;
```
You are correct, the integers could produce the same - its just there because I copied the rules 1:1 from the ST grammar rules.

I'll fix it eventually, yesterday I sort of "finished" the structured text part of the grammar. Now I need to review the generated AST.

**Pull request merged**
