### PR TITLE
Add try-catch-finally exception handling block

### PR DESCRIPTION
**Pull request by nikvoronin**

### CODE REVIEW

**Comment by Serhioromano** [comment]
Try in ST? Where is it used? In what IDE? And why keywords start with `__`?

**Comment by nikvoronin** [comment]
- Why not?
- I know about [CoDeSys 3](https://help.codesys.com/api-content/2/codesys/3.5.13.0/en/_cds_operator_try_catch_finally_endtry/) and [Beckhoff TwinCAT 3](https://infosys.beckhoff.com/content/1033/tc3_plc_intro/36028799548151179.html).
- To highlighting the importance of the try-catch block.

**Comment by Serhioromano** [comment]
Oh my goodness! I totally was not aware of this possibility in Codesys! Thank you. Very nice PR!

**Comment by Serhioromano** [comment]
I've updated the extension to 1.7.3 with your new additions. You can update it in VS Code and use it with your new features.

**Comment by nikvoronin** [comment]
Thank you for your awesome extension!

**Comment by Serhioromano** [comment]
Do not forget to [rate it and give a review](https://marketplace.visualstudio.com/items?itemName=Serhioromano.vscode-st&ssr=false#review-details)!

**Pull request merged**
